dist: trusty
language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
    language: python
    python: "3.6"
    env: PYTHON=3.6 COMPILER="g++-5"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - build-essential
        - cmake
  - os: linux
    compiler: gcc
    language: python
    python: "3.5"
    env: PYTHON=3.5 COMPILER="g++-5"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - build-essential
        - cmake
  - os: linux
    compiler: gcc
    language: python
    python: "3.4"
    env: PYTHON=3.4 COMPILER="g++-5"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - build-essential
        - cmake
  - os: linux
    compiler: clang
    language: python
    python: "3.6"
    env: PYTHON=3.6 COMPILER="clang++"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - build-essential
        - cmake
  - os: linux
    compiler: clang
    language: python
    python: "3.5"
    env: PYTHON=3.5 COMPILER="clang++"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - build-essential
        - cmake
  - os: linux
    compiler: clang
    language: python
    python: "3.4"
    env: PYTHON=3.4 COMPILER="clang++"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - build-essential
        - cmake

before_install:
- which sha256sum
- wget https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2
- echo "5721818253e6a0989583192f96782c4a98eb6204965316df9f5ad75819225ca9  boost_1_66_0.tar.bz2" | sha256sum --check - && tar xvf boost_1_66_0.tar.bz2 > /dev/null 2>&1

script:
- mkdir build
- cd build
- ls
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DBOOST_ROOT=`pwd`/../boost_1_66_0 -DPYBIND11_PYTHON_VERSION=$PYTHON ..
- make
- ctest --output-on-failure
- cd ..
- pip install ./
