dist: trusty
language: cpp

matrix:
  include:
  - os: linux
    language: cpp
    compiler: gcc
    python: "3.6"
    env: COMPILER="g++-5"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - build-essential
        - cmake
  - os: linux
    language: cpp
    compiler: clang
    python: "3.6"
    env: COMPILER="clang++"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - build-essential
        - cmake
  - os: osx
    language: cpp
    compiler: clang

before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update;
    brew install coreutils;
    sudo ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum;
  fi
- which sha256sum

script:
- mkdir build
- cd build
- wget https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2
- echo "5721818253e6a0989583192f96782c4a98eb6204965316df9f5ad75819225ca9  boost_1_66_0.tar.bz2" | sha256sum --check - && tar xvf boost_1_66_0.tar.bz2 > /dev/null 2>&1
- ls
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DBOOST_ROOT=`pwd`/boost_1_66_0 ..
- make
- ctest --output-on-failure
