dist: trusty
language: cpp

matrix:
  include:
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-5"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - build-essential
        - cmake
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - build-essential
        - cmake
  - os: osx
    language: cpp
    compiler: clang

script:
- mkdir build
- cd build
- wget https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2
- tar xvf boost_1_66_0.tar.bz2 > /dev/null 2>&1
- cmake -DCMAKE_INCLUDE_PATH=./boost_1_66_0/boost -DCMAKE_CXX_COMPILER=$COMPILER ..
- make
- ctest --output-on-failure
