dist: trusty
language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
    language: python
    python: "3.6"
    env: PYTHON=3.6 COMPILER="g++-5"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - build-essential
        - cmake
        - python3
        - python3-dev
  - os: linux
    compiler: clang
    language: python
    python: "3.6"
    env: PYTHON=3.6 COMPILER="clang++"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - build-essential
        - cmake
        - python3
        - python3-dev
  - os: osx
    language: cpp
    compiler: clang

before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update;
    brew install coreutils python3;
    sudo ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum;
  fi
- which sha256sum
- wget https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2
- echo "5721818253e6a0989583192f96782c4a98eb6204965316df9f5ad75819225ca9  boost_1_66_0.tar.bz2" | sha256sum --check - && tar xvf boost_1_66_0.tar.bz2 > /dev/null 2>&1

script:
- mkdir build
- cd build
- ls
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DBOOST_ROOT=`pwd`/../boost_1_66_0 -DPYBIND11_PYTHON_VERSION=$PYTHON ..
- make
- ctest --output-on-failure
- cd ..
- pip install ./
